med_comfort/med_comfort/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
]

med_comfort/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
]

med_comfort/pages/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'pages/index.html')

med_comfort/templates/base.html
<!doctype html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Мед комфорт{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/logo.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    {% include 'includes/header.html' %}

    <div class="py-5 container">
      {% block content %}
      {% endblock %}
    </div>

    {% include 'includes/footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

med_comfort/templates/includes/footer.html
{% load static %}
<footer class="py-3 my-4 border-top">
  <div class="container d-flex flex-wrap justify-content-between align-items-center">
    <p class="col-md-4 mb-0 text-body-secondary default_cursor_cs">© 2023 Мед Комфорт</p>

    <a href="{% url 'pages:index' %}" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none default_pointer_cs">
      <img src="{% static 'img/logo.png' %}" alt="Логотип" height="60px">
    </a>

    <ul class="nav col-md-4 justify-content-end default_cursor_cs">
      <li class="nav-item"><a href="{% url 'pages:index' %}" class="nav-link px-2 text-body-secondary default_pointer_cs">Главная</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary default_pointer_cs">Услуги</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary default_pointer_cs">Врачи</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary default_pointer_cs">Режим работы</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary default_pointer_cs">Контакты</a></li>
    </ul>
  </div>
</footer>

med_comfort/templates/includes/header.html
{% load static %}
<header class="p-3 mb-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start default_cursor_cs">
      <a href="{% url 'pages:index' %}" class="d-flex align-items-center mb-2 me-2 mb-lg-0 link-body-emphasis text-decoration-none">
        <img src="{% static 'img/logo.png' %}" alt="Логотип" height="50px">
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 link-body-emphasis">Услуги</a></li>
        <li><a href="#" class="nav-link px-2 link-body-emphasis">Врачи</a></li>
        <li><a href="#" class="nav-link px-2 link-body-emphasis">Режим работы</a></li>
        <li><a href="#" class="nav-link px-2 link-body-emphasis">Контакты</a></li>
      </ul>

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
        <input type="search" class="form-control" placeholder="Поиск..." aria-label="Search">
      </form>
      {% if user.is_authenticated %}
        <div class="dropdown text-end">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
          </a>
          <ul class="dropdown-menu text-small">
            <li><a class="dropdown-item" href="#">New project...</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Sign out</a></li>
          </ul>
        </div>
      {% else %}
        <div class="text-end default_cursor_cs">
          <button type="button" class="btn btn-outline-info me-2 default_pointer_cs">Войти</button>
          <button type="button" class="btn btn-primary default_pointer_cs">Зарегистрироваться</button>
        </div>
      {% endif %}
    </div>
  </div>
</header>

med_comfort/templates/pages/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Мед комфорт
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-4 text-center">
      <img src="{% static 'img/logo.png' %}" alt="Логотип" height="300px">
    </div>
    <div class="col-sm-8">
      <h1 class="text-center mb-4">
        Добро пожаловать в клинику<br>
        "Мед Комфорт"!
      </h1>
      <p class="text-justify">
        Мы - команда профессиональных медицинских экспертов,
        предоставляющих высококачественные медицинские услуги
        в комфортной и дружественной атмосфере. <br>
        Наша цель - заботиться о вашем здоровье и обеспечивать лучшую
        медицинскую помощь в соответствии с вашими потребностями.
        В клинике "Мед Комфорт" мы предлагаем широкий
        спектр услуг, начиная от общей диагностики и лечения
        до специализированных медицинских услуг. <br>
        Мы ждем вас в клинике "Мед Комфорт", где ваше здоровье - наша главная забота.
      </p>
    </div>
  </div>
{% endblock %}